### ISSUE TITLE
Why is the default stateVersion set at 22.05?

### ISSUE THREAD

**Issue by stratosgear** [snowfallorg/templates#3]
When running `nix flake init -t github:snowfallorg/templates#system` I get a stateVersion of 22.05, while I would expect it to be getting the most recent 23.05.

Does it statically default to an older version? And is there a way to overwrite it (apart from manually editing all files)

**Comment by jakehamilton** [comment]
stateVersion is a concept from nixpkgs which allows for otherwise breaking changes in applications. Typically this means the location of some files may be different depending on the stateVersion. Without this feature, any change like that would break everyone's machine on upgrade. You can modify the stateVersion, but you need to be sure that you have checked all of the breaking changes made between releases.

Overall, it is not necessary to change the stateVersion of your machine after you install it.

**Comment by stratosgear** [comment]
Oh, sorry was not very clear....

I read all about the meaning and purpose of the stateVersion (they do have a "scary" warning after all).

I was wondering why on a newly created template file, that is generated when 23.05 is out, would not the generator use the latest version available.  Would it work correctly when I am using 23.05, but my file is pointing to 22.05?

I would assume that when I start a new flake at the end of 2023 when 23.05 is the latest stable, that the 23.05 stateVersion "should" be the default...

**Comment by jakehamilton** [comment]
@stratosgear that would be because nix templates work by doing a git clone and the template hasn't been updated.

**Comment by stratosgear** [comment]
Oh, you mean this: https://github.com/snowfallorg/templates/blob/main/system/systems/x86_64-linux/example/default.nix#L17

So it is a static file. I assumed you, somehow, where creating it dynamically.  Do you see anything wrong if we bump this to [23.11](https://github.com/NixOS/nixpkgs/issues/258640)?

I can PR it if you want! Otherwise feel free to close this issue! 

Thanks!

**Comment by jakehamilton** [comment]
I've updated the `stateVersion` to the latest. It may be useful to update this automatically in the future, but I don't think leaving it will be harmful. Going to close this issue for the time being :+1:
